# -*- coding: utf-8 -*-
"""P1_andres_flores

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AgfRu2U55kR5UJ0T2NC6RnphcIzfc72e
"""

# Remueva los strings vacios de una lista de estring

list_1= ["gatos", "", "perros",  "ratones", ""]
list_1.pop(1)
list_1.pop(3)
print(list_1)

#Añada un nuevo elemento a una lista despues de un elemento especifico
list_2= [1,2,[200,400, [1000, 6000],800],30, 40]
list_2[2][2].insert(1,5000)
print(list_2)

#Cree un nuevo string, usando el primer, tercer y ultimo elemento de un string dado.

str= "Despues de la tempestad, viene la calma"
str_1= str[0] + str[2] + str [-1]
print (str_1)

# Escriba un script para convertir la temperatura dada en dados centigrados a farhrenheit 

temperature_c= 20
temperature_f = temperature_c*(9/5) + 32
print(temperature_f)

#Mezcle los diccionarios en uno

dict_1= {"Diez": 10, "Veinte":20, "Treinta" : 30}
dict_2= {"Treinta": 30, "Cuarenta": 40, "Cincuenta": 50}

dict_1.update(dict_2)

print(dict_1)

#Imprima el resultado de la clave o key "historia", del diccionario dado:

dict_student= {
    "class": {
        "student": {
            "name": "Mike",
            "mark": {
                "physical": 70,
                "history": 80
            }
        }
    }
}

print(dict_student["class"]["student"]["mark"]["history"])

#Cambie la fecha de nacimiento de plantonn del año 427 a.C al año 428 a.C

dict_3= {"nombre": "planton", "pais": "antigua Grecia", "fecha_de_nacimiento": 427, "maestro": "socrates", "alumno": "aristoteles"}
dict_3["fecha_de_nacimiento"] = 428
print (dict_3)