# -*- coding: utf-8 -*-
"""p2_s3_andres_flores

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QKlZckI3A8DQCzHYjjwRFKRSriQheeVw
"""

print("Hola Bienvenid@s \n Esta calculadora sólo permite una operación a la vez \n Y podrá realizar dos operaciones.")


print("Por favor ingrese la operación a realizar")
print(" 1 Suma \n 2 Resta \n 3 Multiplicación \n 4 División \n")



operation = int(input())
number_1 = float(input("  Ingrese el primer valor:   "))
number_2 = float(input("  Ingrese el segundo valor:  "))

if operation == 1:
  result_1= number_1 + number_2
  print("El resultado es: ", result_1)

  d = int(input(" ¿Desea realizar otra operación con este resultado? \n 1 SI \n 2 NO "))
  if d==1:
    e = int(input("Seleccione la opción de su preferencia \n 1 Suma \n 2 Resta \n 3 Multiplicación \n 4 División \n "))
    if e == 1:
      number_3 = float(input("Ingrese el segundo valor:  "))
      g = result_1 + number_3
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")
    
    elif e == 2:
      number_3 = float(input("Ingrese el segundo valor:  "))
      g = result_1 - number_3
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e == 3:
      number_3 = float(input("Ingrese el segundo valor:  "))
      g= result_1 * number_3
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e == 4:
      number_3 = float(input("Ingrese el segundo valor:  "))
      if number_3 == 0:
        number_3 = float(input("El denominador no puede ser = 0 \n Intentelo nuevamente "))
        g= result_1 / number_3
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

      else:
        g= result_1 / number_3
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

    elif d == 2:
      print("Gracias por preferirnos.")
    else:
      print("Opción no válida \n Intételo nuevamente ")



elif operation == 2:

  result_2 = number_1 - number_2
  print("El resultado es: ", result_2)
  
  d = int(input(" ¿Desea realizar otra operación con este resultado? \n 1 SI \n 2 NO "))
  if d == 1:
    e = int(input("Seleccione la opción de su preferencia \n 1 Suma \n 2 Resta \n 3 Multiplicación \n 4 División \n "))

    if e == 1:
      f = float(input("Ingrese el segundo valor:  "))
      g = result_2 + f
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e==2:
      f = float(input("Ingrese el segundo valor:  "))
      g = result_2 - f
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e==3:
      f = float(input("Ingrese el segundo valor:  "))
      g = result_2 * f
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e==4:
      f = float(input("Ingrese el segundo valor:  "))
      if f == 0:
        f = float(input("El denominador no puede ser = 0 \n Intentelo nuevamente  "))
        g = result_2 / f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")
      else:
        g = result_2 / f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

    else:
      print("Opción no válida \n Inténtelo nuevamente ")
    
  elif d==2:
    print("Gracias por preferirnos.")
  else:
    print("Opción no válida \n Inténtelo nuevamente ")

    


elif operation==3:
  result_3 = number_1 * number_2
  print("El resultado es: ", result_3)
  
  d=int(input(" ¿Desea realizar otra operación con este resultado? \n 1 SI \n 2 NO "))
  if d==1:
    e=int(input("Seleccione la opción de su preferencia \n 1 Suma \n 2 Resta \n 3 Multiplicación \n 4 División  \n"))

    if e==1:
      f = float(input("Ingrese el segundo valor:  "))
      g = result_3 + f
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e==2:
      f = float(input("Ingrese el segundo valor:  "))
      g = result_3 - f
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e==3:
      f = float(input("Ingrese el segundo valor:  "))
      g = result_3 * f
      print("El resultado es: ", g)
      print("Gracias por preferirnos.")

    elif e==4:
      f = float(input("Ingrese el segundo valor:  "))
      if f == 0:
        f = float(input("El denominador no puede ser = 0 \n Inténtelo nuevamente "))
        g = result_3 / f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")
      else:
        g = result_3 / f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

    else:
      print("Opción no válida \n Inténtelo nuevamente ")
  elif d==2:
    print("Gracias por preferirnos.")
    




elif operation == 4:
  if number_2 == 0:
    print("El denominador no puede ser = 0")
    print("Inténtelo nuevamente ")

    number_2 = float(input("Ingrese el segundo valor:  "))
    result_4 = number_1 /number_2
    print("El resultado es: ", result_4)
    
    d=int(input(" ¿Desea realizar otra operación con este resultado? \n 1 SI \n 2 NO "))
    if d==1:
      e=int(input("Seleccione la opción de su preferencia \n 1 Suma \n 2 Resta \n 3 Multiplicación \n 4 División \n  "))
      if e==1:
        f=float(input("Ingrese el segundo valor:  "))
        g = result_4 + f
        print("El resultado es: ", g) 
        print("Gracias por preferirnos.")

      elif e==2:
        f = float(input("Ingrese el segundo valor:  "))
        g = result_4 - f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

      elif e==3:
        f = float(input("Ingrese el segundo valor:  "))
        g = result_4 * f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

      elif e==4:
        f = float(input("Ingrese el segundo valor:  "))
        if f == 0:
          f = float(input("El denominador no puede ser = 0 \n Inténtelo nuevamente "))
          g = result_4 / f
          print("El resultado es: ", g)
          print("Gracias por preferirnos.")
        else:
          g = result_4 / f
          print("El resultado es: ", g)
          print("Gracias por preferirnos.")

    elif d==2:
      print("Gracias por preferirnos.") 
    else:
      print("Opción no válida \n Inténtelo nuevamente ")

  else:
    result_4 = number_1 / number_2
    print("El resultado es: ", result_4)
    

    d=int(input(" ¿Desea realizar otra operación con este resultado? \n 1 SI \n 2 NO "))
    if d == 1:
      e=int(input("Seleccione la opción de su preferencia \n 1 Suma \n 2 Resta \n 3 Multiplicación \n 4 División \n  "))

      if e == 1:
        f = float(input("Ingrese el segundo valor:  "))
        g = result_4 + f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

      elif e == 2:
        f = float(input("Ingrese el segundo valor:  "))
        g = result_4 - f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

      elif e == 3:
        f = float(input("Ingrese el segundo valor:  "))
        g = result_4 * f
        print("El resultado es: ", g)
        print("Gracias por preferirnos.")

      elif e == 4:
        f=float(input("Ingrese el segundo valor:  "))
        if f == 0:
          f = float(input("El denominador no puede ser = 0 \n Inténtelo nuevamente "))
          g = result_4 / f
          print("El resultado es: ", g)
          print("Gracias por preferirnos.")
        else:
          g = result_4 / f
          print("El resultado es: ", g)
          print("Gracias por preferirnos.")

    elif d==2:
      print("Gracias por preferirnos.")
    
    else:
      print("Opción no válida \n Inténtelo nuevamente ")
    
else:
  print("Operación a realizar inválida, inténtelo nuevamente ")

