# -*- coding: utf-8 -*-
"""practica_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kqwh6NCsX933DtwhQJ-UhwcZmxrk6Hho
"""

#Practica numero 5

number_of_rows = int(input("Ingrese el numero de filas:  "))
number_of_columns = 2
matrix = []
last_number = 0

for rows in range (1, number_of_rows + 1):
  list= []
  if rows %2 != 0:
    for columns in range (1 , number_of_columns + 1):
      list.append( last_number + columns)

    list.append(list[0] + list[1])
    matrix.append(list)
    last_number = list [1]

  if rows % 2 == 0:
    for columns in range (1, number_of_columns + 1):
      list.append(last_number + columns)

    list.append (list[0] * list[1])
    matrix.append(list)
    last_number = list [1]

matrix_str = ""

for rows in range (number_of_rows):
  string = str(matrix[rows])
  matrix_str += string
  matrix_str += "\n"

with open ("text_matrix.txt", "w") as archive:
  archive.write(matrix_str)

print (matrix_str)